pipeline {
  agent any
  environment {
    XYGENI_TOKEN        = credentials('XYGENI_TOKEN')
    XY_URL              = credentials('XY_URL_demo')
    XY_CRED             = credentials('XY_CRED_demo')
    GH_PAT              = credentials('GH_PAT')
    PROJECT_NAME="Jenkins1"
    PROJECT_HOME="/var/lib/jenkins/workspace/XyTest1/JavaVulnerableLab"
  }
  stages {
    stage('Install Xygeni scanner') {
      steps {
        sh """
        date
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        #curl -L https://get.xygeni.io/latest/scanner/install.sh | \
        #/bin/bash -s -- -t $XYGENI_TOKEN -d $WORKSPACE/scanner
        #curl -L https://get.xygeni.io/latest/scanner/install.sh | \
        #/bin/bash -s -- -u ${env.XY_CRED_USR}  -p ${env.XY_CRED_PSW} -s ${env.XY_URL} -d $WORKSPACE/scanner 
        
        ls -l
        date
        """
      }
    }
    stage('Scan for issues') {
      steps {
        withEnv(["GH_PAT=${env.GH_PAT}"]) {   
          sh """
          echo $GH_PAT
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          $WORKSPACE/scanner/xygeni scan \
            -n $PROJECT_NAME \
            --dir $WORKSPACE -e **/scanner/**
          """
        }
      }
    }
  }
}